############################
## CHANGE THESE
############################

baseURL: "https://mohammedovich.github.io"
title: Mohammed Ibrahim Blog

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
