############################
## CHANGE THESE
############################

baseURL: "https://mohammedovich.github.io"
title: Mohammed Ibrahim

############################
## MISC
############################

googleAnalytics: G-HQF32ZVXNL
enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
