############################
## CHANGE THESE
############################

baseURL: "https://mohammedovich.github.io/mohammedovich.github.io"
title: mohammedovich.github.io

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
