googleAnalytics: G-HQF32ZVXNL
services:
  googleAnalytics:
    id: G-HQF32ZVXNL
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

############################
## Author
############################

author:
  name: Mohammed Ibrahim
  image: author.png
  greeting: "Welcome to my blog :tada:"
  icon: ":wave:"


############################
## Links
############################

links:
  - github: https://github.com/mohammedovich/mohammedovich.github.io
  - link: https://github.com/mohammedovich/mohammedovich.github.io#readme
  # - website: 
  - x-twitter: https://x.com/mohammedovich
  # - mastodon: 
  # - linkedin: 
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - email: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: mohammedovich.github.io
description: "Site built with Qubt & Hugo"
images:
  - thumbnail.png

params:
  comments: true