googleAnalytics: G-HQF32ZVXNL
services:
  googleAnalytics:
    id: G-HQF32ZVXNL
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

############################
## Author
############################

author:
  name: Mohammed Ibrahim
  image: author.png
  greeting: "Welcome to my blog :tada:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/mohammedovich/mohammedovich.github.io
  - link: https://github.com/mohammedovich/mohammedovich.github.io#readme
  # - website: 
  - x-twitter: https://x.com/mohammedovich
  # - mastodon: 
  - linkedin: https://www.linkedin.com/in/mohammedovich/

###############################
## OpenGraph & Twitter Cards
###############################

title: mohammedovich.github.io
description: "Site built with Qubt & Hugo"
images:
  - thumbnail.png

comments: true
